export const COPING_TOOLS = [
  {
    id: 'breathing',
    title: '4-7-8 Breathing',
    emoji: '🌬️',
    description: 'Slow your nervous system in three counts.',
    howItHelps: 'Stimulates the parasympathetic nervous system via prolonged exhalation, lowering heart rate and soothing adrenaline.',
    isInteractive: true,
    tags: ['anxiety', 'low', 'panic', 'stress'],
  },
  {
    id: 'sensory-reset',
    title: 'Sensory Reset',
    emoji: '💧',
    description: 'Cold water, a soft texture, a strong smell.',
    howItHelps: 'Engages the mammalian dive reflex and breaks repetitive cognitive spirals by anchoring sensations in physical reality.',
    isInteractive: false,
    tags: ['anxiety', 'overwhelmed', 'low', 'grounding'],
  },
  {
    id: 'meditation',
    title: 'Meditation',
    emoji: '🧘',
    description: 'Sit with your breath for five minutes.',
    howItHelps: 'Cultivates non-judgmental awareness of internal thoughts without getting swept up in their emotional current.',
    isInteractive: false,
    tags: ['calm', 'low', 'reflection'],
  },
  {
    id: 'journaling',
    title: 'Journaling',
    emoji: '✍️',
    description: "Put words to what's inside.",
    howItHelps: 'Externalizes tangled thoughts onto paper, activating verbal centers in the brain and reducing amygdala reactivity.',
    isInteractive: false,
    tags: ['low', 'sadness', 'clarity'],
  },
  {
    id: 'reading',
    title: 'Reading',
    emoji: '📖',
    description: 'Lose yourself in a few pages.',
    howItHelps: 'Gently shifts cognitive focus away from personal rumination into a structured, narrative-driven mental space.',
    isInteractive: false,
    tags: ['quiet', 'distraction', 'low'],
  },
  {
    id: 'music',
    title: 'Music',
    emoji: '🎵',
    description: 'Let sound shift your state.',
    howItHelps: 'Acoustic harmonies synchronize brainwave activity and trigger dopamine and endorphin release in emotional circuits.',
    isInteractive: false,
    tags: ['comfort', 'mood-boost'],
  },
  {
    id: 'walking',
    title: 'Walking',
    emoji: '🚶',
    description: 'Move your body, clear your head.',
    howItHelps: 'Bilateral stimulation from walking and natural optical flow lowers cortisol and sparks perspective-taking.',
    isInteractive: false,
    tags: ['movement', 'low', 'fresh-air'],
  },
  {
    id: 'nature',
    title: 'Nature',
    emoji: '🌿',
    description: 'Step outside, even for two minutes.',
    howItHelps: 'Phytoncides from green plants and exposure to natural daylight reset circadian stress hormones and ground vision.',
    isInteractive: false,
    tags: ['grounding', 'low', 'rest'],
  },
  {
    id: 'social-connection',
    title: 'Social Connection',
    emoji: '🤝',
    description: 'Reach out to one person.',
    howItHelps: 'Social safety cues and vocal warmth elevate oxytocin, neutralizing the neurochemical isolation of despair.',
    isInteractive: false,
    tags: ['connection', 'support', 'low'],
  },
  {
    id: 'creative-expression',
    title: 'Creative Expression',
    emoji: '🎨',
    description: 'Draw, write, hum — anything.',
    howItHelps: 'Channel abstract emotional energy into tangible forms without needing logical justifications or performance standards.',
    isInteractive: false,
    tags: ['expression', 'release'],
  },
  {
    id: 'exercise',
    title: 'Exercise',
    emoji: '🏃',
    description: 'Raise your heart rate gently.',
    howItHelps: 'Physical exertion metabolizes excess adrenaline and floods the bloodstream with neuroprotective BDNF and endorphins.',
    isInteractive: false,
    tags: ['energy', 'release'],
  },
  {
    id: 'mindful-eating',
    title: 'Mindful Eating',
    emoji: '🍵',
    description: 'Eat or drink one thing slowly, with full attention.',
    howItHelps: 'Tuning into taste, aroma, warmth, and texture returns somatic awareness to the mouth and throat, calming tension.',
    isInteractive: false,
    tags: ['somatic', 'calm'],
  },
];
