export const HELPLINES = [
  {
    id: 'tele-manas',
    name: 'Tele-MANAS',
    phone: '14416',
    altPhone: '1800 891 4416',
    timing: '24×7, Free & Confidential',
    languages: 'Hindi, English & 20+ Regional Languages',
    description: 'National Tele Mental Health Programme of India, providing instant, free psychosocial support by trained counselors.',
    isPrimary: true,
  },
  {
    id: 'vandrevala',
    name: 'Vandrevala Foundation',
    phone: '+91 9999 666 555',
    timing: '24×7, Free',
    languages: 'English, Hindi & Major Indian Languages',
    description: 'Round-the-clock free mental health crisis intervention and counseling service across India.',
  },
  {
    id: 'kiran',
    name: 'KIRAN Helpline',
    phone: '1800-599-0019',
    timing: '24×7, Toll-Free',
    languages: '13 Languages',
    description: 'Ministry of Social Justice and Empowerment helpline for psychological support, distress management, and mental health emergencies.',
  },
  {
    id: 'aasra',
    name: 'AASRA',
    phone: '+91 98204 66726',
    timing: '24×7, Free & Confidential',
    languages: 'English, Hindi',
    description: 'Crisis intervention and suicide prevention helpline providing compassionate, non-judgmental emotional support.',
  },
  {
    id: 'icall',
    name: 'iCall (TISS Mumbai)',
    phone: '9152987821',
    altPhone: '022-25521111',
    timing: 'Mon–Sat, 10:00 AM – 8:00 PM',
    languages: 'English, Hindi, Marathi, Bengali, Tamil, etc.',
    description: 'Psychosocial helpline run by Tata Institute of Social Sciences, offering professional, ethical counseling.',
  },
  {
    id: 'sneha',
    name: 'Sneha India',
    phone: '+91 44 2464 0050',
    timing: '24×7, Free',
    languages: 'English, Tamil',
    description: 'A suicide prevention organization offering unconditional emotional support for individuals experiencing acute distress.',
  },
  {
    id: 'parivarthan',
    name: 'Parivarthan Counselling Helpline',
    phone: '+91 76766 02602',
    timing: 'Mon–Fri, 1:00 PM – 10:00 PM',
    languages: 'English, Hindi, Kannada, Tamil, Telugu',
    description: 'Free, confidential telephonic counseling service staffed by trained and supervised mental health practitioners.',
  },
  {
    id: 'nimhans',
    name: 'NIMHANS Psychosocial Helpline',
    phone: '080-46110007',
    timing: '24×7, Free',
    languages: 'English, Hindi & Multiple Regional Languages',
    description: 'Apex healthcare institute providing expert psychological first aid and mental health triage.',
  },
];
