spring:
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://127.0.0.1:27017/mindease}
      database: ${SPRING_DATA_MONGODB_DATABASE:}

logging:
  level:
    com.mindease: DEBUG
    org.springframework.security: INFO
    org.springframework.data.mongodb: INFO
